Create website
SamroodAli/new-york-times-article-clone pull request #1
Opened 2021-02-17 16:33 UTC by SamroodAli

2021-02-17 20:55 UTC, LamiaSristy requested changes
# Status: Change Required. ♻️

Hello @SamroodAli, I can see lots of effort in this project. You have done very well until now. Congratulation on that. 👏 👏 👏 

## The highlights: 
* Your `git-flow` is correct. 💯 
*  Setting up `linters` is correct. 💯 
*  The project is looking great, you followed all the basics of `HTML5&CSS` concepts. 👍 
*  Nice work on the `Navbar` part ⭐ 
*  Nice work on `embedded images and video`. ⭐ 

## What to do next:  

**Now let's work on some requirements, which need to complete in order to get approval.**
**Please remember all the checklist needs to add**

## [REQUIRED]

- [x]  Please add a meaningful title and a short description to the Pull Request.

**README.md**
- [x]  Add a screenshot of the project in the browser.
- [x]  Add a working live demo.
- [x]  In the `Getting Started` section add instructions for download and locally run your project.

**Design Part**
- [x] Elements aligned with a combination of all three techniques float, flex, grid. I can see flex and grid but you need to use [float](https://css-tricks.com/all-about-floats/) too.
- [x]  The `Editor's picks` section is not at the starting of the page, please reposition this. 
![screencapture-file-F-TSE-new-york-times-article-clone-create-website-index-html-2021-02-17-21_23_43](https://user-images.githubusercontent.com/56501603/108263495-a6902700-7166-11eb-9775-2327a47f783a.png)
You can check the real design [here](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

- [x]  The `The Theory of Inflation` section also needs to retouch.
![ss2](https://user-images.githubusercontent.com/56501603/108263833-07b7fa80-7167-11eb-8a89-383311cd4d69.png)
Please compare the red marked area with the real design, and make the changes.

- [x] There is a border in the starting of the **Bottom part**, compare two images:

Your project 👇 
![ss3](https://user-images.githubusercontent.com/56501603/108264549-f7544f80-7167-11eb-8012-952ceebc5048.png)

The main site 👇 
![ss4](https://user-images.githubusercontent.com/56501603/108264577-fe7b5d80-7167-11eb-8ae4-2d51aa21ef65.png)


**In the bottom part**
- [x]  The `Most popular` has all the link components. 
- [x]  The `More in Space and Astronomy` part you need to add a margin between the articles.
- [x] The `SUBSCRIBE` section add some margin and padding.
- [x]  The Footer is missing in your design. Check the red arrow 👇 
![ss5](https://user-images.githubusercontent.com/56501603/108265847-9ded2000-7169-11eb-959a-983f9917f8ff.png)
- [x]  Go to Home Page » link is missing. check the previous image, check the red box. ☝️  


**Changes to make in CSS file**
- [x] Bad CSS Practice: You are using repeated code like `display: grid;` 16 times, `display: flex;` 7 times,  and many more. This is bad CSS practice also against the DRY rule. Instead of this, you can write a single class like `.grid { display: grid;  }`
- [x]  Remove the commented line 33 from the stylesheet.

## 

**OOOh!! That's a huge list!! But don't worry. It's normal** ☺️ 

**Please add all this to your project and then ask again for a CRR.**

Feel free to reach me on slack @lamiasristy 🙋

**Keep up the spirit always.** 

Happy Coding 💻

2021-02-17 20:58 UTC, LamiaSristy commented on style.css
> +}
You are using all these stylings many times differently, you can make a new class named `.flex-center` and use it.

2021-02-17 23:33 UTC, LamiaSristy commented on index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" />
It's a good practice to use ./ before the href.
<link rel="stylesheet" href="./style.css">

2021-02-18 11:34 UTC, SamroodAli commented
I have completed the requirements and I updated the readme file.
There was an issue with the alignment of the readme which I only fixed after submitting the pull request.
But it is fixed now.
Thank you @LamiaSristy for the code review, your requirements were very clear and I enjoyed improving my code.
I hope I have met all the requirements

2021-02-18 16:43 UTC, GzimAsani approved these changes
# Status: PROJECT APPROVED :+1: : :100:  
## Hello **Team** 👋, good job implementing all the requirements asked from the previous reviewer :muscle:, you have met all the requirements so go ahead and merge this pull request.

_Ps: Don't forget to submit the project completion form_  


### HAPPY CODING :computer:

2021-02-19 02:06 UTC, merged

2021-02-19 03:10 UTC, SamroodAli commented
> # Status: PROJECT APPROVED 👍 : 💯
> ## Hello **Team** 👋, good job implementing all the requirements asked from the previous reviewer 💪, you have met all the requirements so go ahead and merge this pull request.
> _Ps: Don't forget to submit the project completion form_
> 
> ### HAPPY CODING 💻

Thank You